name: Build Base Image for NLP Spacy

# Define environment variables
env:
  ARTIFACT_NAME: com.verifika.service.ml.ignoring.helper.base
  DOCKERFILE_PATH: ignoring-helper/Dockerfile.base-image

# Manual workflow trigger
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL}}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build and push base image to registry
      run: docker build . --file $DOCKERFILE_PATH --tag ${{ secrets.DOCKER_REGISTRY_URL }}/$ARTIFACT_NAME:${{ github.run_number }} --tag ${{ secrets.DOCKER_REGISTRY_URL }}/$ARTIFACT_NAME:latest
    - name: Push base image to registry
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/$ARTIFACT_NAME:${{ github.run_number }}; docker push ${{ secrets.DOCKER_REGISTRY_URL }}/$ARTIFACT_NAME:latest
